spring:
  application:
    name: garage
  datasource:
    url: jdbc:h2:mem:db_garage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      pool-name: HikariGaragePool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
  h2:
    console:
      enabled: true
      path: /h2-console   # this will be the URL path

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  kafka:
    bootstrap-servers:
      - localhost:9093
    consumer:
      group-id: rahile.abdelmounim.garage
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10000
      properties:
        spring:
          json:
            trusted.packages: rahile.abdelmounim.garage.evenement.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    main: rahile.abdelmounim.garage.EVT_GARAGE_MAIN

